name: Scheduled Telegram Message

on:
  schedule:
    - cron: '0 13 * * *' # This cron schedule runs every day at 13:00 UTC (21:00 SGT)
  workflow_dispatch: # This allows the workflow to be manually triggered

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Message
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ env.TELEGRAM_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ env.TELEGRAM_CHAT_ID }} \
          -d text="Good Evening! Let's finish the day with a Roody Update!" \
          -d reply_markup='{
            "keyboard":[
              [{"text":"Uploading a Poods Pic! 📷"}],
              [{"text":"A Poods Picture Please! 🐕‍🦺"}]
            ],
            "one_time_keyboard":true,
            "resize_keyboard":true
          }'
