name: Scheduled Telegram Message

on:
  schedule:
    - cron: '0 2 * * *' # This cron schedule runs every day at 2:00 UTC (10:00 SGT)
  workflow_dispatch: # This allows the workflow to be manually triggered

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Message
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ env.TELEGRAM_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ env.TELEGRAM_CHAT_ID }} \
          -d text="Good Morning! Let's start the day with a Roody Update!" \
          -d reply_markup='{
            "inline_keyboard":[
              [{"text":"Upload a Photo! 📷"}],
              [{"text":"I'm busy. Pick-a-Poods! 🐕‍🦺"}]
            ]
          }'
